---
sidebar: sidebar 
permalink: trident-use/anf.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Você pode configurar o Azure NetApp Files como back-end para o Astra Trident. É possível anexar volumes NAS e SMB usando um back-end do Azure NetApp Files. 
---
= Configurar um back-end do Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o Azure NetApp Files como back-end para o Astra Trident. É possível anexar volumes NFS e SMB usando um back-end do Azure NetApp Files.



== Detalhes do driver Azure NetApp Files

O Astra Trident fornece os seguintes drivers de storage Azure NetApp Files para se comunicar com o cluster. Os modos de acesso suportados são: _ReadWriteOnce_ (RWO), _ReadOnlyMuy_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Condutor | Protocolo | VolumeMode | Modos de acesso suportados | Sistemas de arquivos suportados 


| `azure-netapp-files`  a| 
NFS, SMB
 a| 
Sistema de ficheiros
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


== Considerações

* O serviço Azure NetApp Files não oferece suporte a volumes menores que 100 GB. O Astra Trident cria automaticamente volumes de 100 GB se um volume menor for solicitado.
* O Astra Trident é compatível com volumes SMB montados em pods executados apenas em nós do Windows.

